<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_silang_subs_window</name>
   <tag></tag>
   <elementGuidId>be437aa4-0c4d-4f35-9b77-8a84971676e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-button-1454703513202 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-button-1454703513202']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a889e0e-a1eb-4a8c-88fd-fc66f141c414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>a101752a-3166-41a7-bcf6-21c3b0d3fa56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-button-1454703513202&quot;)/span[1]</value>
      <webElementGuid>56506f19-48c1-4d3a-8fac-e75ce29c4d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='close-button-1454703513202']/span</value>
      <webElementGuid>b36246d4-a4ab-4056-98a0-27f9b13fd7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Thank you! We', &quot;'&quot;, 'll be in touch')])[1]/following::span[1]</value>
      <webElementGuid>b7b196e4-19d7-47a9-8aa3-08ffd3ba8c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBSCRIBE'])[1]/following::span[1]</value>
      <webElementGuid>dbd1db66-969d-47f6-b24f-cadfa4b524bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>fb7cbedf-dd3a-4b6f-9809-3d4e207d0c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div/div[2]/div/span</value>
      <webElementGuid>8b24139b-901c-4050-aa23-3b1b872e8273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>c1800669-3eb9-4ae0-b630-0cfae6819a05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
