<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subs_window</name>
   <tag></tag>
   <elementGuidId>977e4e13-8e3d-4253-abe1-0a2b4dc5f970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wrap-responsive-image-17236201843890</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrap-responsive-image-17236201843890']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ab4c7f1-b683-4f91-a8e8-10c49f7b0ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wrap-responsive-image-17236201843890</value>
      <webElementGuid>7be7431c-6567-445f-b41a-47658ac2cb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-selectable-element ins-element-wrap ins-element-image ins-template-image ins-element-grid-wrap ins-sample-element-wrapper ins-element-select-menu</value>
      <webElementGuid>1324efd8-8946-47d1-9571-b1b3655f444f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap-responsive-image-17236201843890&quot;)</value>
      <webElementGuid>6c1db48e-0cd8-46f6-94b7-08639ee465bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wrap-responsive-image-17236201843890']</value>
      <webElementGuid>5ba07454-98e5-4a76-93b6-1ee956738fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ins-wrap-block-1723620184389000']/div</value>
      <webElementGuid>658b5a3f-d416-428d-b8e4-200bac832f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try-On'])[1]/following::div[12]</value>
      <webElementGuid>3737a8c4-5fd9-470e-8114-311178762f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Virtual Try⁠-⁠On'])[1]/following::div[13]</value>
      <webElementGuid>94915686-e4c8-475f-a991-bbe7a86193c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BE THE FIRST TO GET INFORMED!'])[1]/preceding::div[7]</value>
      <webElementGuid>b8226377-fbe5-4140-8b2b-663a9adbe365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe to our WhatsApp and get Exclusive Launch Alert &amp; Special Offer!'])[1]/preceding::div[11]</value>
      <webElementGuid>82c5e1d3-324b-4919-b834-c6bd18c9c835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div/div/form/div/div/div/div/div/div/div</value>
      <webElementGuid>2d096acf-dd4c-436f-8a59-95f46371e07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wrap-responsive-image-17236201843890']</value>
      <webElementGuid>fe767a9c-427e-4503-95f4-443b32a3213d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
